# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 622)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1032, 622))
        MainWindow.setMaximumSize(QtCore.QSize(1032, 622))
        MainWindow.setStyleSheet("QMainWindow {background-color: rgb(240, 240, 240)}")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 101, 22))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_on = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_on.setGeometry(QtCore.QRect(921, 523, 85, 27))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_on.setFont(font)
        self.pushButton_on.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.pushButton_on.setObjectName("pushButton_on")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(19, 532, 81, 17))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.groupBox_ar = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_ar.setGeometry(QtCore.QRect(81, 120, 162, 146))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_ar.sizePolicy().hasHeightForWidth())
        self.groupBox_ar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_ar.setFont(font)
        self.groupBox_ar.setStyleSheet("QGroupBox { border:none}")
        self.groupBox_ar.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_ar.setFlat(True)
        self.groupBox_ar.setCheckable(True)
        self.groupBox_ar.setObjectName("groupBox_ar")
        self.frame_ar = QtWidgets.QFrame(self.groupBox_ar)
        self.frame_ar.setEnabled(True)
        self.frame_ar.setGeometry(QtCore.QRect(4, 24, 156, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_ar.sizePolicy().hasHeightForWidth())
        self.frame_ar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame_ar.setFont(font)
        self.frame_ar.setStyleSheet("")
        self.frame_ar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_ar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ar.setLineWidth(1)
        self.frame_ar.setObjectName("frame_ar")
        self.horizontalSlider_ar = QtWidgets.QSlider(self.frame_ar)
        self.horizontalSlider_ar.setGeometry(QtCore.QRect(12, 30, 131, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_ar.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_ar.setSizePolicy(sizePolicy)
        self.horizontalSlider_ar.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"selection-background-color: rgb(0, 114, 189);\n"
"")
        self.horizontalSlider_ar.setMaximum(100)
        self.horizontalSlider_ar.setSingleStep(0)
        self.horizontalSlider_ar.setProperty("value", 67)
        self.horizontalSlider_ar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_ar.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_ar.setObjectName("horizontalSlider_ar")
        self.label_19 = QtWidgets.QLabel(self.frame_ar)
        self.label_19.setGeometry(QtCore.QRect(55, 8, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.doubleSpinBox_ar = QtWidgets.QDoubleSpinBox(self.frame_ar)
        self.doubleSpinBox_ar.setGeometry(QtCore.QRect(10, 4, 49, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_ar.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_ar.setSizePolicy(sizePolicy)
        self.doubleSpinBox_ar.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox_ar.setFont(font)
        self.doubleSpinBox_ar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_ar.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_ar.setDecimals(1)
        self.doubleSpinBox_ar.setMaximum(3.0)
        self.doubleSpinBox_ar.setSingleStep(0.1)
        self.doubleSpinBox_ar.setProperty("value", 2.0)
        self.doubleSpinBox_ar.setObjectName("doubleSpinBox_ar")
        self.label_20 = QtWidgets.QLabel(self.frame_ar)
        self.label_20.setGeometry(QtCore.QRect(47, 62, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_ar = QtWidgets.QLabel(self.frame_ar)
        self.label_ar.setEnabled(True)
        self.label_ar.setGeometry(QtCore.QRect(10, 58, 35, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ar.sizePolicy().hasHeightForWidth())
        self.label_ar.setSizePolicy(sizePolicy)
        self.label_ar.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.label_ar.setFont(font)
        self.label_ar.setAutoFillBackground(False)
        self.label_ar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_ar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_ar.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ar.setObjectName("label_ar")
        self.frame_ar.raise_()
        self.groupBox_al = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_al.setGeometry(QtCore.QRect(254, 120, 162, 146))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_al.sizePolicy().hasHeightForWidth())
        self.groupBox_al.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_al.setFont(font)
        self.groupBox_al.setStyleSheet("QGroupBox { border:none}")
        self.groupBox_al.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_al.setFlat(True)
        self.groupBox_al.setCheckable(True)
        self.groupBox_al.setObjectName("groupBox_al")
        self.frame_al = QtWidgets.QFrame(self.groupBox_al)
        self.frame_al.setGeometry(QtCore.QRect(4, 24, 154, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_al.sizePolicy().hasHeightForWidth())
        self.frame_al.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame_al.setFont(font)
        self.frame_al.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_al.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_al.setLineWidth(1)
        self.frame_al.setObjectName("frame_al")
        self.horizontalSlider_al = QtWidgets.QSlider(self.frame_al)
        self.horizontalSlider_al.setGeometry(QtCore.QRect(12, 30, 131, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_al.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_al.setSizePolicy(sizePolicy)
        self.horizontalSlider_al.setStyleSheet("selection-background-color: rgb(220, 52, 50, 255);\n"
"")
        self.horizontalSlider_al.setMaximum(100)
        self.horizontalSlider_al.setSingleStep(0)
        self.horizontalSlider_al.setProperty("value", 67)
        self.horizontalSlider_al.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_al.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_al.setObjectName("horizontalSlider_al")
        self.label_25 = QtWidgets.QLabel(self.frame_al)
        self.label_25.setGeometry(QtCore.QRect(55, 8, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.doubleSpinBox_al = QtWidgets.QDoubleSpinBox(self.frame_al)
        self.doubleSpinBox_al.setGeometry(QtCore.QRect(10, 4, 49, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_al.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_al.setSizePolicy(sizePolicy)
        self.doubleSpinBox_al.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_al.setFont(font)
        self.doubleSpinBox_al.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_al.setDecimals(1)
        self.doubleSpinBox_al.setMaximum(3.0)
        self.doubleSpinBox_al.setSingleStep(0.1)
        self.doubleSpinBox_al.setProperty("value", 2.0)
        self.doubleSpinBox_al.setObjectName("doubleSpinBox_al")
        self.label_26 = QtWidgets.QLabel(self.frame_al)
        self.label_26.setGeometry(QtCore.QRect(47, 62, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_al = QtWidgets.QLabel(self.frame_al)
        self.label_al.setEnabled(True)
        self.label_al.setGeometry(QtCore.QRect(10, 58, 35, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_al.sizePolicy().hasHeightForWidth())
        self.label_al.setSizePolicy(sizePolicy)
        self.label_al.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_al.setFont(font)
        self.label_al.setAutoFillBackground(False)
        self.label_al.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_al.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_al.setAlignment(QtCore.Qt.AlignCenter)
        self.label_al.setObjectName("label_al")
        self.label_t_run = QtWidgets.QLabel(self.centralWidget)
        self.label_t_run.setEnabled(True)
        self.label_t_run.setGeometry(QtCore.QRect(86, 528, 51, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_t_run.sizePolicy().hasHeightForWidth())
        self.label_t_run.setSizePolicy(sizePolicy)
        self.label_t_run.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.label_t_run.setFont(font)
        self.label_t_run.setAutoFillBackground(False)
        self.label_t_run.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(240, 240, 240);\n"
"border-color: rgb(196, 193, 189);")
        self.label_t_run.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_t_run.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t_run.setObjectName("label_t_run")
        self.label_21 = QtWidgets.QLabel(self.centralWidget)
        self.label_21.setGeometry(QtCore.QRect(128, 530, 41, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_ant = QtWidgets.QLabel(self.centralWidget)
        self.label_ant.setGeometry(QtCore.QRect(14, 50, 471, 451))
        self.label_ant.setText("")
        self.label_ant.setPixmap(QtGui.QPixmap("img/anterior.png"))
        self.label_ant.setScaledContents(True)
        self.label_ant.setObjectName("label_ant")
        self.label_alr_color_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_2.setGeometry(QtCore.QRect(1140, 10, 161, 131))
        self.label_alr_color_2.setStyleSheet("background-color: rgba(0, 114, 189);")
        self.label_alr_color_2.setText("")
        self.label_alr_color_2.setObjectName("label_alr_color_2")
        self.label_alr_color_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_3.setGeometry(QtCore.QRect(1140, 430, 161, 131))
        self.label_alr_color_3.setStyleSheet("background-color: rgba(119, 172, 48);")
        self.label_alr_color_3.setText("")
        self.label_alr_color_3.setObjectName("label_alr_color_3")
        self.label_alr_color_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_5.setGeometry(QtCore.QRect(1140, 150, 161, 131))
        self.label_alr_color_5.setStyleSheet("background-color: rgba(216, 83, 25);")
        self.label_alr_color_5.setText("")
        self.label_alr_color_5.setObjectName("label_alr_color_5")
        self.label_alr_color_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_6.setGeometry(QtCore.QRect(1140, 290, 161, 131))
        self.label_alr_color_6.setStyleSheet("background-color: rgba(236, 177, 32);")
        self.label_alr_color_6.setText("")
        self.label_alr_color_6.setObjectName("label_alr_color_6")
        self.label_alr_color_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_7.setGeometry(QtCore.QRect(1310, 290, 161, 131))
        self.label_alr_color_7.setStyleSheet("background-color: rgba(236, 177, 32, 200);")
        self.label_alr_color_7.setText("")
        self.label_alr_color_7.setObjectName("label_alr_color_7")
        self.label_alr_color_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_8.setGeometry(QtCore.QRect(1310, 430, 161, 131))
        self.label_alr_color_8.setStyleSheet("background-color: rgba(119, 172, 48, 200);")
        self.label_alr_color_8.setText("")
        self.label_alr_color_8.setObjectName("label_alr_color_8")
        self.label_alr_color_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_9.setGeometry(QtCore.QRect(1310, 150, 161, 131))
        self.label_alr_color_9.setStyleSheet("background-color: rgba(216, 83, 25, 200);")
        self.label_alr_color_9.setText("")
        self.label_alr_color_9.setObjectName("label_alr_color_9")
        self.label_alr_color_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_10.setGeometry(QtCore.QRect(1310, 10, 161, 131))
        self.label_alr_color_10.setStyleSheet("background-color: rgba(0, 114, 189, 200);")
        self.label_alr_color_10.setText("")
        self.label_alr_color_10.setObjectName("label_alr_color_10")
        self.label_alr_color_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_11.setGeometry(QtCore.QRect(1310, 570, 161, 131))
        self.label_alr_color_11.setStyleSheet("background-color: rgba(236, 177, 32, 100);\n"
"background-color: rgb(170, 170, 255, 150);")
        self.label_alr_color_11.setText("")
        self.label_alr_color_11.setObjectName("label_alr_color_11")
        self.label_alr_color_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_12.setGeometry(QtCore.QRect(1140, 570, 161, 131))
        self.label_alr_color_12.setStyleSheet("background-color: rgb(144, 144, 216);\n"
"")
        self.label_alr_color_12.setText("")
        self.label_alr_color_12.setObjectName("label_alr_color_12")
        self.label_t_run_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_t_run_2.setEnabled(True)
        self.label_t_run_2.setGeometry(QtCore.QRect(190, 650, 51, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_t_run_2.sizePolicy().hasHeightForWidth())
        self.label_t_run_2.setSizePolicy(sizePolicy)
        self.label_t_run_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_t_run_2.setFont(font)
        self.label_t_run_2.setAutoFillBackground(False)
        self.label_t_run_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_t_run_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_t_run_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t_run_2.setObjectName("label_t_run_2")
        self.label_35 = QtWidgets.QLabel(self.centralWidget)
        self.label_35.setGeometry(QtCore.QRect(260, 650, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.label_post = QtWidgets.QLabel(self.centralWidget)
        self.label_post.setGeometry(QtCore.QRect(540, 50, 471, 451))
        self.label_post.setText("")
        self.label_post.setPixmap(QtGui.QPixmap("img/posterior.png"))
        self.label_post.setScaledContents(True)
        self.label_post.setObjectName("label_post")
        self.groupBox_pl = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_pl.setGeometry(QtCore.QRect(607, 120, 162, 146))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_pl.sizePolicy().hasHeightForWidth())
        self.groupBox_pl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_pl.setFont(font)
        self.groupBox_pl.setStyleSheet("QGroupBox { border:none}")
        self.groupBox_pl.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_pl.setFlat(True)
        self.groupBox_pl.setCheckable(True)
        self.groupBox_pl.setChecked(True)
        self.groupBox_pl.setObjectName("groupBox_pl")
        self.frame_pl = QtWidgets.QFrame(self.groupBox_pl)
        self.frame_pl.setGeometry(QtCore.QRect(4, 24, 154, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pl.sizePolicy().hasHeightForWidth())
        self.frame_pl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame_pl.setFont(font)
        self.frame_pl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pl.setLineWidth(1)
        self.frame_pl.setObjectName("frame_pl")
        self.horizontalSlider_pl = QtWidgets.QSlider(self.frame_pl)
        self.horizontalSlider_pl.setGeometry(QtCore.QRect(12, 30, 131, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_pl.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_pl.setSizePolicy(sizePolicy)
        self.horizontalSlider_pl.setStyleSheet("selection-background-color: rgb(216, 83, 25);\n"
"selection-background-color: rgb(250, 231, 81, 255);\n"
"selection-background-color: rgb(220, 52, 50, 255);\n"
"\n"
"")
        self.horizontalSlider_pl.setMaximum(100)
        self.horizontalSlider_pl.setSingleStep(0)
        self.horizontalSlider_pl.setProperty("value", 67)
        self.horizontalSlider_pl.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pl.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_pl.setObjectName("horizontalSlider_pl")
        self.label_28 = QtWidgets.QLabel(self.frame_pl)
        self.label_28.setGeometry(QtCore.QRect(55, 8, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.doubleSpinBox_pl = QtWidgets.QDoubleSpinBox(self.frame_pl)
        self.doubleSpinBox_pl.setGeometry(QtCore.QRect(10, 4, 49, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_pl.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_pl.setSizePolicy(sizePolicy)
        self.doubleSpinBox_pl.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_pl.setFont(font)
        self.doubleSpinBox_pl.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_pl.setDecimals(1)
        self.doubleSpinBox_pl.setMaximum(3.0)
        self.doubleSpinBox_pl.setSingleStep(0.1)
        self.doubleSpinBox_pl.setProperty("value", 2.0)
        self.doubleSpinBox_pl.setObjectName("doubleSpinBox_pl")
        self.label_29 = QtWidgets.QLabel(self.frame_pl)
        self.label_29.setGeometry(QtCore.QRect(47, 62, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.label_pl = QtWidgets.QLabel(self.frame_pl)
        self.label_pl.setEnabled(True)
        self.label_pl.setGeometry(QtCore.QRect(10, 58, 35, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pl.sizePolicy().hasHeightForWidth())
        self.label_pl.setSizePolicy(sizePolicy)
        self.label_pl.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_pl.setFont(font)
        self.label_pl.setAutoFillBackground(False)
        self.label_pl.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_pl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_pl.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pl.setObjectName("label_pl")
        self.groupBox_pr = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_pr.setGeometry(QtCore.QRect(780, 120, 162, 146))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_pr.sizePolicy().hasHeightForWidth())
        self.groupBox_pr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_pr.setFont(font)
        self.groupBox_pr.setStyleSheet("QGroupBox { border:none}")
        self.groupBox_pr.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_pr.setFlat(True)
        self.groupBox_pr.setCheckable(True)
        self.groupBox_pr.setObjectName("groupBox_pr")
        self.frame_pr = QtWidgets.QFrame(self.groupBox_pr)
        self.frame_pr.setEnabled(True)
        self.frame_pr.setGeometry(QtCore.QRect(4, 24, 156, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pr.sizePolicy().hasHeightForWidth())
        self.frame_pr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame_pr.setFont(font)
        self.frame_pr.setStyleSheet("")
        self.frame_pr.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pr.setLineWidth(1)
        self.frame_pr.setObjectName("frame_pr")
        self.horizontalSlider_pr = QtWidgets.QSlider(self.frame_pr)
        self.horizontalSlider_pr.setGeometry(QtCore.QRect(12, 30, 131, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_pr.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_pr.setSizePolicy(sizePolicy)
        self.horizontalSlider_pr.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"selection-background-color: rgb(0, 114, 189);\n"
"")
        self.horizontalSlider_pr.setMaximum(100)
        self.horizontalSlider_pr.setSingleStep(0)
        self.horizontalSlider_pr.setProperty("value", 67)
        self.horizontalSlider_pr.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pr.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_pr.setObjectName("horizontalSlider_pr")
        self.label_30 = QtWidgets.QLabel(self.frame_pr)
        self.label_30.setGeometry(QtCore.QRect(55, 8, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.doubleSpinBox_pr = QtWidgets.QDoubleSpinBox(self.frame_pr)
        self.doubleSpinBox_pr.setGeometry(QtCore.QRect(10, 4, 49, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_pr.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_pr.setSizePolicy(sizePolicy)
        self.doubleSpinBox_pr.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox_pr.setFont(font)
        self.doubleSpinBox_pr.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_pr.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_pr.setDecimals(1)
        self.doubleSpinBox_pr.setMaximum(3.0)
        self.doubleSpinBox_pr.setSingleStep(0.1)
        self.doubleSpinBox_pr.setProperty("value", 2.0)
        self.doubleSpinBox_pr.setObjectName("doubleSpinBox_pr")
        self.label_31 = QtWidgets.QLabel(self.frame_pr)
        self.label_31.setGeometry(QtCore.QRect(47, 62, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.label_pr = QtWidgets.QLabel(self.frame_pr)
        self.label_pr.setEnabled(True)
        self.label_pr.setGeometry(QtCore.QRect(10, 58, 35, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pr.sizePolicy().hasHeightForWidth())
        self.label_pr.setSizePolicy(sizePolicy)
        self.label_pr.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.label_pr.setFont(font)
        self.label_pr.setAutoFillBackground(False)
        self.label_pr.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_pr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_pr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pr.setObjectName("label_pr")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(724, 20, 101, 22))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_alr_color_13 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_13.setGeometry(QtCore.QRect(1310, 720, 161, 131))
        self.label_alr_color_13.setStyleSheet("background-color: rgb(100, 0, 0, 150);")
        self.label_alr_color_13.setText("")
        self.label_alr_color_13.setObjectName("label_alr_color_13")
        self.label_alr_color_14 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_14.setGeometry(QtCore.QRect(1140, 720, 161, 131))
        self.label_alr_color_14.setStyleSheet("background-color: rgba(216, 83, 25);")
        self.label_alr_color_14.setText("")
        self.label_alr_color_14.setObjectName("label_alr_color_14")
        self.label_color_pl = QtWidgets.QLabel(self.centralWidget)
        self.label_color_pl.setGeometry(QtCore.QRect(613, 115, 150, 231))
        self.label_color_pl.setStyleSheet("background-color: rgba(216, 83, 25, 100);\n"
"background-color: rgb(231, 179, 156, 150);\n"
"background-color: rgba(221, 117, 72, 140);\n"
"background-color: rgb(250, 231, 81, 150);\n"
"background-color: rgb(220, 52, 50, 125);\n"
"border-radius: 10px;")
        self.label_color_pl.setText("")
        self.label_color_pl.setObjectName("label_color_pl")
        self.label_color_pr = QtWidgets.QLabel(self.centralWidget)
        self.label_color_pr.setGeometry(QtCore.QRect(786, 115, 150, 231))
        self.label_color_pr.setStyleSheet("background-color: rgba(0, 170, 255, 100);\n"
"background-color: rgb(52, 141, 200, 150);\n"
"background-color: rgb(53, 151, 255, 130);\n"
"border-radius: 10px;")
        self.label_color_pr.setText("")
        self.label_color_pr.setObjectName("label_color_pr")
        self.label_color_pul_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_color_pul_2.setGeometry(QtCore.QRect(400, 620, 150, 122))
        self.label_color_pul_2.setStyleSheet("background-color: rgb(136, 212, 152, 175);\n"
"border-radius: 10px;")
        self.label_color_pul_2.setText("")
        self.label_color_pul_2.setObjectName("label_color_pul_2")
        self.label_aur_color_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_aur_color_3.setGeometry(QtCore.QRect(570, 620, 150, 122))
        self.label_aur_color_3.setStyleSheet("background-color: rgb(170, 170, 255, 150);\n"
"border-radius: 10px;")
        self.label_aur_color_3.setText("")
        self.label_aur_color_3.setObjectName("label_aur_color_3")
        self.label_color_al = QtWidgets.QLabel(self.centralWidget)
        self.label_color_al.setGeometry(QtCore.QRect(260, 115, 150, 231))
        self.label_color_al.setStyleSheet("background-color: rgba(216, 83, 25, 100);\n"
"background-color: rgb(231, 179, 156, 150);\n"
"background-color: rgba(221, 117, 72, 140);\n"
"background-color: rgb(220, 52, 50, 125);\n"
"border-radius: 10px;")
        self.label_color_al.setText("")
        self.label_color_al.setObjectName("label_color_al")
        self.label_color_ar = QtWidgets.QLabel(self.centralWidget)
        self.label_color_ar.setGeometry(QtCore.QRect(87, 115, 150, 231))
        self.label_color_ar.setStyleSheet("background-color: rgba(0, 170, 255, 100);\n"
"background-color: rgb(52, 141, 200, 150);\n"
"background-color: rgb(53, 151, 255, 130);\n"
"border-radius: 10px;")
        self.label_color_ar.setText("")
        self.label_color_ar.setObjectName("label_color_ar")
        self.label_ant.raise_()
        self.label_t_run.raise_()
        self.label_color_ar.raise_()
        self.label_color_al.raise_()
        self.label_post.raise_()
        self.label_color_pul_2.raise_()
        self.label_color_pr.raise_()
        self.label_color_pl.raise_()
        self.label.raise_()
        self.pushButton_on.raise_()
        self.label_9.raise_()
        self.groupBox_ar.raise_()
        self.groupBox_al.raise_()
        self.label_21.raise_()
        self.label_alr_color_2.raise_()
        self.label_alr_color_3.raise_()
        self.label_alr_color_5.raise_()
        self.label_alr_color_6.raise_()
        self.label_alr_color_7.raise_()
        self.label_alr_color_8.raise_()
        self.label_alr_color_9.raise_()
        self.label_alr_color_10.raise_()
        self.label_alr_color_11.raise_()
        self.label_alr_color_12.raise_()
        self.label_t_run_2.raise_()
        self.label_35.raise_()
        self.groupBox_pl.raise_()
        self.label_4.raise_()
        self.label_alr_color_13.raise_()
        self.label_alr_color_14.raise_()
        self.groupBox_pr.raise_()
        self.label_aur_color_3.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1032, 25))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Anterior"))
        self.pushButton_on.setText(_translate("MainWindow", "Run"))
        self.label_9.setText(_translate("MainWindow", "Run Time:"))
        self.groupBox_ar.setTitle(_translate("MainWindow", "Right"))
        self.label_19.setText(_translate("MainWindow", "setpoint (psi)"))
        self.label_20.setText(_translate("MainWindow", "current (psi)"))
        self.label_ar.setText(_translate("MainWindow", "0.0"))
        self.groupBox_al.setTitle(_translate("MainWindow", "Left  "))
        self.label_25.setText(_translate("MainWindow", "setpoint (psi)"))
        self.label_26.setText(_translate("MainWindow", "current (psi)"))
        self.label_al.setText(_translate("MainWindow", "0.0"))
        self.label_t_run.setText(_translate("MainWindow", "0.0"))
        self.label_21.setText(_translate("MainWindow", "(min)"))
        self.label_t_run_2.setText(_translate("MainWindow", "0.0"))
        self.label_35.setText(_translate("MainWindow", "(psi) accumulator"))
        self.groupBox_pl.setTitle(_translate("MainWindow", "Left  "))
        self.label_28.setText(_translate("MainWindow", "setpoint (psi)"))
        self.label_29.setText(_translate("MainWindow", "current (psi)"))
        self.label_pl.setText(_translate("MainWindow", "0.0"))
        self.groupBox_pr.setTitle(_translate("MainWindow", "Right"))
        self.label_30.setText(_translate("MainWindow", "setpoint (psi)"))
        self.label_31.setText(_translate("MainWindow", "current (psi)"))
        self.label_pr.setText(_translate("MainWindow", "0.0"))
        self.label_4.setText(_translate("MainWindow", "Posterior"))

