# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 622)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1032, 622))
        MainWindow.setMaximumSize(QtCore.QSize(1032, 622))
        MainWindow.setStyleSheet("QMainWindow {background-color: rgb(240, 240, 240)}")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 101, 22))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_on = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_on.setGeometry(QtCore.QRect(921, 523, 85, 27))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_on.setFont(font)
        self.pushButton_on.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.pushButton_on.setObjectName("pushButton_on")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(19, 532, 81, 17))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.groupBox_alr = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_alr.setGeometry(QtCore.QRect(76, 267, 162, 146))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_alr.sizePolicy().hasHeightForWidth())
        self.groupBox_alr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_alr.setFont(font)
        self.groupBox_alr.setStyleSheet("QGroupBox { border:none}")
        self.groupBox_alr.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_alr.setCheckable(True)
        self.groupBox_alr.setObjectName("groupBox_alr")
        self.frame_alr = QtWidgets.QFrame(self.groupBox_alr)
        self.frame_alr.setGeometry(QtCore.QRect(4, 24, 154, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_alr.sizePolicy().hasHeightForWidth())
        self.frame_alr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame_alr.setFont(font)
        self.frame_alr.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_alr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_alr.setLineWidth(1)
        self.frame_alr.setObjectName("frame_alr")
        self.horizontalSlider_alr = QtWidgets.QSlider(self.frame_alr)
        self.horizontalSlider_alr.setGeometry(QtCore.QRect(12, 30, 131, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_alr.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_alr.setSizePolicy(sizePolicy)
        self.horizontalSlider_alr.setStyleSheet("selection-background-color: rgb(141, 70, 212);")
        self.horizontalSlider_alr.setMaximum(100)
        self.horizontalSlider_alr.setSingleStep(0)
        self.horizontalSlider_alr.setProperty("value", 67)
        self.horizontalSlider_alr.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_alr.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_alr.setObjectName("horizontalSlider_alr")
        self.label_16 = QtWidgets.QLabel(self.frame_alr)
        self.label_16.setGeometry(QtCore.QRect(55, 8, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.doubleSpinBox_alr = QtWidgets.QDoubleSpinBox(self.frame_alr)
        self.doubleSpinBox_alr.setGeometry(QtCore.QRect(10, 4, 49, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_alr.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_alr.setSizePolicy(sizePolicy)
        self.doubleSpinBox_alr.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox_alr.setFont(font)
        self.doubleSpinBox_alr.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_alr.setDecimals(1)
        self.doubleSpinBox_alr.setMaximum(3.0)
        self.doubleSpinBox_alr.setSingleStep(0.1)
        self.doubleSpinBox_alr.setProperty("value", 2.0)
        self.doubleSpinBox_alr.setObjectName("doubleSpinBox_alr")
        self.label_17 = QtWidgets.QLabel(self.frame_alr)
        self.label_17.setGeometry(QtCore.QRect(47, 62, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.label_alr = QtWidgets.QLabel(self.frame_alr)
        self.label_alr.setEnabled(True)
        self.label_alr.setGeometry(QtCore.QRect(10, 58, 35, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_alr.sizePolicy().hasHeightForWidth())
        self.label_alr.setSizePolicy(sizePolicy)
        self.label_alr.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.label_alr.setFont(font)
        self.label_alr.setAutoFillBackground(False)
        self.label_alr.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_alr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_alr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_alr.setObjectName("label_alr")
        self.groupBox_aur = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_aur.setGeometry(QtCore.QRect(76, 99, 162, 146))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_aur.sizePolicy().hasHeightForWidth())
        self.groupBox_aur.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_aur.setFont(font)
        self.groupBox_aur.setStyleSheet("QGroupBox { border:none}")
        self.groupBox_aur.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_aur.setFlat(True)
        self.groupBox_aur.setCheckable(True)
        self.groupBox_aur.setObjectName("groupBox_aur")
        self.frame_aur = QtWidgets.QFrame(self.groupBox_aur)
        self.frame_aur.setEnabled(True)
        self.frame_aur.setGeometry(QtCore.QRect(4, 24, 156, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_aur.sizePolicy().hasHeightForWidth())
        self.frame_aur.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame_aur.setFont(font)
        self.frame_aur.setStyleSheet("")
        self.frame_aur.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_aur.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_aur.setLineWidth(1)
        self.frame_aur.setObjectName("frame_aur")
        self.horizontalSlider_aur = QtWidgets.QSlider(self.frame_aur)
        self.horizontalSlider_aur.setGeometry(QtCore.QRect(12, 30, 131, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_aur.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_aur.setSizePolicy(sizePolicy)
        self.horizontalSlider_aur.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"selection-background-color: rgb(0, 114, 189);\n"
"")
        self.horizontalSlider_aur.setMaximum(100)
        self.horizontalSlider_aur.setSingleStep(0)
        self.horizontalSlider_aur.setProperty("value", 67)
        self.horizontalSlider_aur.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_aur.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_aur.setObjectName("horizontalSlider_aur")
        self.label_19 = QtWidgets.QLabel(self.frame_aur)
        self.label_19.setGeometry(QtCore.QRect(55, 8, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.doubleSpinBox_aur = QtWidgets.QDoubleSpinBox(self.frame_aur)
        self.doubleSpinBox_aur.setGeometry(QtCore.QRect(10, 4, 49, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_aur.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_aur.setSizePolicy(sizePolicy)
        self.doubleSpinBox_aur.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox_aur.setFont(font)
        self.doubleSpinBox_aur.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_aur.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_aur.setDecimals(1)
        self.doubleSpinBox_aur.setMaximum(3.0)
        self.doubleSpinBox_aur.setSingleStep(0.1)
        self.doubleSpinBox_aur.setProperty("value", 2.0)
        self.doubleSpinBox_aur.setObjectName("doubleSpinBox_aur")
        self.label_20 = QtWidgets.QLabel(self.frame_aur)
        self.label_20.setGeometry(QtCore.QRect(47, 62, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_aur = QtWidgets.QLabel(self.frame_aur)
        self.label_aur.setEnabled(True)
        self.label_aur.setGeometry(QtCore.QRect(10, 58, 35, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_aur.sizePolicy().hasHeightForWidth())
        self.label_aur.setSizePolicy(sizePolicy)
        self.label_aur.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.label_aur.setFont(font)
        self.label_aur.setAutoFillBackground(False)
        self.label_aur.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_aur.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_aur.setAlignment(QtCore.Qt.AlignCenter)
        self.label_aur.setObjectName("label_aur")
        self.groupBox_all = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_all.setGeometry(QtCore.QRect(266, 267, 162, 146))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_all.sizePolicy().hasHeightForWidth())
        self.groupBox_all.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_all.setFont(font)
        self.groupBox_all.setStyleSheet("QGroupBox { border:none}")
        self.groupBox_all.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_all.setCheckable(True)
        self.groupBox_all.setObjectName("groupBox_all")
        self.frame_all = QtWidgets.QFrame(self.groupBox_all)
        self.frame_all.setGeometry(QtCore.QRect(4, 24, 154, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_all.sizePolicy().hasHeightForWidth())
        self.frame_all.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame_all.setFont(font)
        self.frame_all.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_all.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_all.setLineWidth(1)
        self.frame_all.setObjectName("frame_all")
        self.horizontalSlider_all = QtWidgets.QSlider(self.frame_all)
        self.horizontalSlider_all.setGeometry(QtCore.QRect(12, 30, 131, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_all.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_all.setSizePolicy(sizePolicy)
        self.horizontalSlider_all.setStyleSheet("selection-background-color: rgb(119, 172, 48);\n"
"selection-background-color: rgb(0, 170, 0);")
        self.horizontalSlider_all.setMaximum(100)
        self.horizontalSlider_all.setSingleStep(0)
        self.horizontalSlider_all.setProperty("value", 67)
        self.horizontalSlider_all.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_all.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_all.setObjectName("horizontalSlider_all")
        self.label_22 = QtWidgets.QLabel(self.frame_all)
        self.label_22.setGeometry(QtCore.QRect(55, 8, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.doubleSpinBox_all = QtWidgets.QDoubleSpinBox(self.frame_all)
        self.doubleSpinBox_all.setGeometry(QtCore.QRect(10, 4, 49, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_all.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_all.setSizePolicy(sizePolicy)
        self.doubleSpinBox_all.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox_all.setFont(font)
        self.doubleSpinBox_all.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_all.setDecimals(1)
        self.doubleSpinBox_all.setMaximum(3.0)
        self.doubleSpinBox_all.setSingleStep(0.1)
        self.doubleSpinBox_all.setProperty("value", 2.0)
        self.doubleSpinBox_all.setObjectName("doubleSpinBox_all")
        self.label_23 = QtWidgets.QLabel(self.frame_all)
        self.label_23.setGeometry(QtCore.QRect(47, 62, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_all = QtWidgets.QLabel(self.frame_all)
        self.label_all.setEnabled(True)
        self.label_all.setGeometry(QtCore.QRect(10, 58, 35, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_all.sizePolicy().hasHeightForWidth())
        self.label_all.setSizePolicy(sizePolicy)
        self.label_all.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.label_all.setFont(font)
        self.label_all.setAutoFillBackground(False)
        self.label_all.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_all.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_all.setAlignment(QtCore.Qt.AlignCenter)
        self.label_all.setObjectName("label_all")
        self.groupBox_aul = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_aul.setGeometry(QtCore.QRect(266, 99, 162, 146))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_aul.sizePolicy().hasHeightForWidth())
        self.groupBox_aul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_aul.setFont(font)
        self.groupBox_aul.setStyleSheet("QGroupBox { border:none}")
        self.groupBox_aul.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_aul.setFlat(True)
        self.groupBox_aul.setCheckable(True)
        self.groupBox_aul.setObjectName("groupBox_aul")
        self.frame_aul = QtWidgets.QFrame(self.groupBox_aul)
        self.frame_aul.setGeometry(QtCore.QRect(4, 24, 154, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_aul.sizePolicy().hasHeightForWidth())
        self.frame_aul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame_aul.setFont(font)
        self.frame_aul.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_aul.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_aul.setLineWidth(1)
        self.frame_aul.setObjectName("frame_aul")
        self.horizontalSlider_aul = QtWidgets.QSlider(self.frame_aul)
        self.horizontalSlider_aul.setGeometry(QtCore.QRect(12, 30, 131, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_aul.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_aul.setSizePolicy(sizePolicy)
        self.horizontalSlider_aul.setStyleSheet("selection-background-color: rgb(220, 52, 50, 255);\n"
"")
        self.horizontalSlider_aul.setMaximum(100)
        self.horizontalSlider_aul.setSingleStep(0)
        self.horizontalSlider_aul.setProperty("value", 67)
        self.horizontalSlider_aul.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_aul.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_aul.setObjectName("horizontalSlider_aul")
        self.label_25 = QtWidgets.QLabel(self.frame_aul)
        self.label_25.setGeometry(QtCore.QRect(55, 8, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.doubleSpinBox_aul = QtWidgets.QDoubleSpinBox(self.frame_aul)
        self.doubleSpinBox_aul.setGeometry(QtCore.QRect(10, 4, 49, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_aul.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_aul.setSizePolicy(sizePolicy)
        self.doubleSpinBox_aul.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_aul.setFont(font)
        self.doubleSpinBox_aul.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_aul.setDecimals(1)
        self.doubleSpinBox_aul.setMaximum(3.0)
        self.doubleSpinBox_aul.setSingleStep(0.1)
        self.doubleSpinBox_aul.setProperty("value", 2.0)
        self.doubleSpinBox_aul.setObjectName("doubleSpinBox_aul")
        self.label_26 = QtWidgets.QLabel(self.frame_aul)
        self.label_26.setGeometry(QtCore.QRect(47, 62, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_aul = QtWidgets.QLabel(self.frame_aul)
        self.label_aul.setEnabled(True)
        self.label_aul.setGeometry(QtCore.QRect(10, 58, 35, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_aul.sizePolicy().hasHeightForWidth())
        self.label_aul.setSizePolicy(sizePolicy)
        self.label_aul.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_aul.setFont(font)
        self.label_aul.setAutoFillBackground(False)
        self.label_aul.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_aul.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_aul.setAlignment(QtCore.Qt.AlignCenter)
        self.label_aul.setObjectName("label_aul")
        self.label_t_run = QtWidgets.QLabel(self.centralWidget)
        self.label_t_run.setEnabled(True)
        self.label_t_run.setGeometry(QtCore.QRect(86, 528, 51, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_t_run.sizePolicy().hasHeightForWidth())
        self.label_t_run.setSizePolicy(sizePolicy)
        self.label_t_run.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.label_t_run.setFont(font)
        self.label_t_run.setAutoFillBackground(False)
        self.label_t_run.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(240, 240, 240);\n"
"border-color: rgb(196, 193, 189);")
        self.label_t_run.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_t_run.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t_run.setObjectName("label_t_run")
        self.label_21 = QtWidgets.QLabel(self.centralWidget)
        self.label_21.setGeometry(QtCore.QRect(128, 529, 41, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_ant = QtWidgets.QLabel(self.centralWidget)
        self.label_ant.setGeometry(QtCore.QRect(14, 50, 471, 451))
        self.label_ant.setText("")
        self.label_ant.setPixmap(QtGui.QPixmap("img/anterior.png"))
        self.label_ant.setScaledContents(True)
        self.label_ant.setObjectName("label_ant")
        self.label_alr_color_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_2.setGeometry(QtCore.QRect(1140, 10, 161, 131))
        self.label_alr_color_2.setStyleSheet("background-color: rgba(0, 114, 189);")
        self.label_alr_color_2.setText("")
        self.label_alr_color_2.setObjectName("label_alr_color_2")
        self.label_alr_color_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_3.setGeometry(QtCore.QRect(1140, 430, 161, 131))
        self.label_alr_color_3.setStyleSheet("background-color: rgba(119, 172, 48);")
        self.label_alr_color_3.setText("")
        self.label_alr_color_3.setObjectName("label_alr_color_3")
        self.label_alr_color_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_5.setGeometry(QtCore.QRect(1140, 150, 161, 131))
        self.label_alr_color_5.setStyleSheet("background-color: rgba(216, 83, 25);")
        self.label_alr_color_5.setText("")
        self.label_alr_color_5.setObjectName("label_alr_color_5")
        self.label_alr_color_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_6.setGeometry(QtCore.QRect(1140, 290, 161, 131))
        self.label_alr_color_6.setStyleSheet("background-color: rgba(236, 177, 32);")
        self.label_alr_color_6.setText("")
        self.label_alr_color_6.setObjectName("label_alr_color_6")
        self.label_alr_color_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_7.setGeometry(QtCore.QRect(1310, 290, 161, 131))
        self.label_alr_color_7.setStyleSheet("background-color: rgba(236, 177, 32, 200);")
        self.label_alr_color_7.setText("")
        self.label_alr_color_7.setObjectName("label_alr_color_7")
        self.label_alr_color_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_8.setGeometry(QtCore.QRect(1310, 430, 161, 131))
        self.label_alr_color_8.setStyleSheet("background-color: rgba(119, 172, 48, 200);")
        self.label_alr_color_8.setText("")
        self.label_alr_color_8.setObjectName("label_alr_color_8")
        self.label_alr_color_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_9.setGeometry(QtCore.QRect(1310, 150, 161, 131))
        self.label_alr_color_9.setStyleSheet("background-color: rgba(216, 83, 25, 200);")
        self.label_alr_color_9.setText("")
        self.label_alr_color_9.setObjectName("label_alr_color_9")
        self.label_alr_color_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_10.setGeometry(QtCore.QRect(1310, 10, 161, 131))
        self.label_alr_color_10.setStyleSheet("background-color: rgba(0, 114, 189, 200);")
        self.label_alr_color_10.setText("")
        self.label_alr_color_10.setObjectName("label_alr_color_10")
        self.label_alr_color_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_11.setGeometry(QtCore.QRect(1310, 570, 161, 131))
        self.label_alr_color_11.setStyleSheet("background-color: rgba(236, 177, 32, 100);\n"
"background-color: rgb(170, 170, 255, 150);")
        self.label_alr_color_11.setText("")
        self.label_alr_color_11.setObjectName("label_alr_color_11")
        self.label_alr_color_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_12.setGeometry(QtCore.QRect(1140, 570, 161, 131))
        self.label_alr_color_12.setStyleSheet("background-color: rgb(144, 144, 216);\n"
"")
        self.label_alr_color_12.setText("")
        self.label_alr_color_12.setObjectName("label_alr_color_12")
        self.label_t_run_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_t_run_2.setEnabled(True)
        self.label_t_run_2.setGeometry(QtCore.QRect(190, 650, 51, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_t_run_2.sizePolicy().hasHeightForWidth())
        self.label_t_run_2.setSizePolicy(sizePolicy)
        self.label_t_run_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_t_run_2.setFont(font)
        self.label_t_run_2.setAutoFillBackground(False)
        self.label_t_run_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_t_run_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_t_run_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t_run_2.setObjectName("label_t_run_2")
        self.label_35 = QtWidgets.QLabel(self.centralWidget)
        self.label_35.setGeometry(QtCore.QRect(260, 650, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.label_post = QtWidgets.QLabel(self.centralWidget)
        self.label_post.setGeometry(QtCore.QRect(540, 50, 471, 451))
        self.label_post.setText("")
        self.label_post.setPixmap(QtGui.QPixmap("img/posterior.png"))
        self.label_post.setScaledContents(True)
        self.label_post.setObjectName("label_post")
        self.groupBox_pul = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_pul.setGeometry(QtCore.QRect(598, 99, 162, 146))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_pul.sizePolicy().hasHeightForWidth())
        self.groupBox_pul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_pul.setFont(font)
        self.groupBox_pul.setStyleSheet("QGroupBox { border:none}")
        self.groupBox_pul.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_pul.setFlat(True)
        self.groupBox_pul.setCheckable(True)
        self.groupBox_pul.setChecked(True)
        self.groupBox_pul.setObjectName("groupBox_pul")
        self.frame_pul = QtWidgets.QFrame(self.groupBox_pul)
        self.frame_pul.setGeometry(QtCore.QRect(4, 24, 154, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pul.sizePolicy().hasHeightForWidth())
        self.frame_pul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame_pul.setFont(font)
        self.frame_pul.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pul.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pul.setLineWidth(1)
        self.frame_pul.setObjectName("frame_pul")
        self.horizontalSlider_pul = QtWidgets.QSlider(self.frame_pul)
        self.horizontalSlider_pul.setGeometry(QtCore.QRect(12, 30, 131, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_pul.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_pul.setSizePolicy(sizePolicy)
        self.horizontalSlider_pul.setStyleSheet("selection-background-color: rgb(216, 83, 25);\n"
"selection-background-color: rgb(250, 231, 81, 255);\n"
"")
        self.horizontalSlider_pul.setMaximum(100)
        self.horizontalSlider_pul.setSingleStep(0)
        self.horizontalSlider_pul.setProperty("value", 67)
        self.horizontalSlider_pul.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pul.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_pul.setObjectName("horizontalSlider_pul")
        self.label_28 = QtWidgets.QLabel(self.frame_pul)
        self.label_28.setGeometry(QtCore.QRect(55, 8, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.doubleSpinBox_pul = QtWidgets.QDoubleSpinBox(self.frame_pul)
        self.doubleSpinBox_pul.setGeometry(QtCore.QRect(10, 4, 49, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_pul.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_pul.setSizePolicy(sizePolicy)
        self.doubleSpinBox_pul.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_pul.setFont(font)
        self.doubleSpinBox_pul.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_pul.setDecimals(1)
        self.doubleSpinBox_pul.setMaximum(3.0)
        self.doubleSpinBox_pul.setSingleStep(0.1)
        self.doubleSpinBox_pul.setProperty("value", 2.0)
        self.doubleSpinBox_pul.setObjectName("doubleSpinBox_pul")
        self.label_29 = QtWidgets.QLabel(self.frame_pul)
        self.label_29.setGeometry(QtCore.QRect(47, 62, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.label_pul = QtWidgets.QLabel(self.frame_pul)
        self.label_pul.setEnabled(True)
        self.label_pul.setGeometry(QtCore.QRect(10, 58, 35, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pul.sizePolicy().hasHeightForWidth())
        self.label_pul.setSizePolicy(sizePolicy)
        self.label_pul.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_pul.setFont(font)
        self.label_pul.setAutoFillBackground(False)
        self.label_pul.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_pul.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_pul.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pul.setObjectName("label_pul")
        self.groupBox_pur = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_pur.setGeometry(QtCore.QRect(788, 99, 162, 146))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_pur.sizePolicy().hasHeightForWidth())
        self.groupBox_pur.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_pur.setFont(font)
        self.groupBox_pur.setStyleSheet("QGroupBox { border:none}")
        self.groupBox_pur.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_pur.setFlat(True)
        self.groupBox_pur.setCheckable(True)
        self.groupBox_pur.setObjectName("groupBox_pur")
        self.frame_pur = QtWidgets.QFrame(self.groupBox_pur)
        self.frame_pur.setEnabled(True)
        self.frame_pur.setGeometry(QtCore.QRect(4, 24, 156, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pur.sizePolicy().hasHeightForWidth())
        self.frame_pur.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame_pur.setFont(font)
        self.frame_pur.setStyleSheet("")
        self.frame_pur.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pur.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pur.setLineWidth(1)
        self.frame_pur.setObjectName("frame_pur")
        self.horizontalSlider_pur = QtWidgets.QSlider(self.frame_pur)
        self.horizontalSlider_pur.setGeometry(QtCore.QRect(12, 30, 131, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_pur.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_pur.setSizePolicy(sizePolicy)
        self.horizontalSlider_pur.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"selection-background-color: rgb(0, 114, 189);\n"
"")
        self.horizontalSlider_pur.setMaximum(100)
        self.horizontalSlider_pur.setSingleStep(0)
        self.horizontalSlider_pur.setProperty("value", 67)
        self.horizontalSlider_pur.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pur.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_pur.setObjectName("horizontalSlider_pur")
        self.label_30 = QtWidgets.QLabel(self.frame_pur)
        self.label_30.setGeometry(QtCore.QRect(55, 8, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.doubleSpinBox_pur = QtWidgets.QDoubleSpinBox(self.frame_pur)
        self.doubleSpinBox_pur.setGeometry(QtCore.QRect(10, 4, 49, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_pur.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_pur.setSizePolicy(sizePolicy)
        self.doubleSpinBox_pur.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox_pur.setFont(font)
        self.doubleSpinBox_pur.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_pur.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_pur.setDecimals(1)
        self.doubleSpinBox_pur.setMaximum(3.0)
        self.doubleSpinBox_pur.setSingleStep(0.1)
        self.doubleSpinBox_pur.setProperty("value", 2.0)
        self.doubleSpinBox_pur.setObjectName("doubleSpinBox_pur")
        self.label_31 = QtWidgets.QLabel(self.frame_pur)
        self.label_31.setGeometry(QtCore.QRect(47, 62, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.label_pur = QtWidgets.QLabel(self.frame_pur)
        self.label_pur.setEnabled(True)
        self.label_pur.setGeometry(QtCore.QRect(10, 58, 35, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pur.sizePolicy().hasHeightForWidth())
        self.label_pur.setSizePolicy(sizePolicy)
        self.label_pur.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.label_pur.setFont(font)
        self.label_pur.setAutoFillBackground(False)
        self.label_pur.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_pur.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_pur.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pur.setObjectName("label_pur")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(724, 20, 101, 22))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_alr_color_13 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_13.setGeometry(QtCore.QRect(1310, 720, 161, 131))
        self.label_alr_color_13.setStyleSheet("background-color: rgb(100, 0, 0, 150);")
        self.label_alr_color_13.setText("")
        self.label_alr_color_13.setObjectName("label_alr_color_13")
        self.label_alr_color_14 = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color_14.setGeometry(QtCore.QRect(1140, 720, 161, 131))
        self.label_alr_color_14.setStyleSheet("background-color: rgba(216, 83, 25);")
        self.label_alr_color_14.setText("")
        self.label_alr_color_14.setObjectName("label_alr_color_14")
        self.label_color_pul = QtWidgets.QLabel(self.centralWidget)
        self.label_color_pul.setGeometry(QtCore.QRect(604, 94, 150, 122))
        self.label_color_pul.setStyleSheet("background-color: rgba(216, 83, 25, 100);\n"
"background-color: rgb(231, 179, 156, 150);\n"
"background-color: rgba(221, 117, 72, 140);\n"
"background-color: rgb(250, 231, 81, 150);\n"
"border-radius: 10px;")
        self.label_color_pul.setText("")
        self.label_color_pul.setObjectName("label_color_pul")
        self.label_aur_color_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_aur_color_2.setGeometry(QtCore.QRect(794, 94, 150, 122))
        self.label_aur_color_2.setStyleSheet("background-color: rgba(0, 170, 255, 100);\n"
"background-color: rgb(52, 141, 200, 150);\n"
"background-color: rgb(53, 151, 255, 130);\n"
"border-radius: 10px;")
        self.label_aur_color_2.setText("")
        self.label_aur_color_2.setObjectName("label_aur_color_2")
        self.groupBox_pll = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_pll.setGeometry(QtCore.QRect(600, 267, 162, 146))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_pll.sizePolicy().hasHeightForWidth())
        self.groupBox_pll.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_pll.setFont(font)
        self.groupBox_pll.setStyleSheet("QGroupBox { border:none}")
        self.groupBox_pll.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_pll.setFlat(True)
        self.groupBox_pll.setCheckable(True)
        self.groupBox_pll.setChecked(True)
        self.groupBox_pll.setObjectName("groupBox_pll")
        self.frame_pll = QtWidgets.QFrame(self.groupBox_pll)
        self.frame_pll.setGeometry(QtCore.QRect(4, 24, 154, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pll.sizePolicy().hasHeightForWidth())
        self.frame_pll.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame_pll.setFont(font)
        self.frame_pll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pll.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pll.setLineWidth(1)
        self.frame_pll.setObjectName("frame_pll")
        self.horizontalSlider_pll = QtWidgets.QSlider(self.frame_pll)
        self.horizontalSlider_pll.setGeometry(QtCore.QRect(12, 30, 131, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_pll.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_pll.setSizePolicy(sizePolicy)
        self.horizontalSlider_pll.setStyleSheet("selection-background-color: rgb(0, 170, 0);")
        self.horizontalSlider_pll.setMaximum(100)
        self.horizontalSlider_pll.setSingleStep(0)
        self.horizontalSlider_pll.setProperty("value", 67)
        self.horizontalSlider_pll.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pll.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_pll.setObjectName("horizontalSlider_pll")
        self.label_36 = QtWidgets.QLabel(self.frame_pll)
        self.label_36.setGeometry(QtCore.QRect(55, 8, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.doubleSpinBox_pll = QtWidgets.QDoubleSpinBox(self.frame_pll)
        self.doubleSpinBox_pll.setGeometry(QtCore.QRect(10, 4, 49, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_pll.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_pll.setSizePolicy(sizePolicy)
        self.doubleSpinBox_pll.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_pll.setFont(font)
        self.doubleSpinBox_pll.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_pll.setDecimals(1)
        self.doubleSpinBox_pll.setMaximum(3.0)
        self.doubleSpinBox_pll.setSingleStep(0.1)
        self.doubleSpinBox_pll.setProperty("value", 2.0)
        self.doubleSpinBox_pll.setObjectName("doubleSpinBox_pll")
        self.label_37 = QtWidgets.QLabel(self.frame_pll)
        self.label_37.setGeometry(QtCore.QRect(47, 62, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.label_pll = QtWidgets.QLabel(self.frame_pll)
        self.label_pll.setEnabled(True)
        self.label_pll.setGeometry(QtCore.QRect(10, 58, 35, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pll.sizePolicy().hasHeightForWidth())
        self.label_pll.setSizePolicy(sizePolicy)
        self.label_pll.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_pll.setFont(font)
        self.label_pll.setAutoFillBackground(False)
        self.label_pll.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_pll.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_pll.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pll.setObjectName("label_pll")
        self.groupBox_plr = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_plr.setGeometry(QtCore.QRect(790, 267, 162, 146))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_plr.sizePolicy().hasHeightForWidth())
        self.groupBox_plr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_plr.setFont(font)
        self.groupBox_plr.setStyleSheet("QGroupBox { border:none}")
        self.groupBox_plr.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_plr.setFlat(True)
        self.groupBox_plr.setCheckable(True)
        self.groupBox_plr.setObjectName("groupBox_plr")
        self.frame_plr = QtWidgets.QFrame(self.groupBox_plr)
        self.frame_plr.setEnabled(True)
        self.frame_plr.setGeometry(QtCore.QRect(4, 24, 156, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_plr.sizePolicy().hasHeightForWidth())
        self.frame_plr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame_plr.setFont(font)
        self.frame_plr.setStyleSheet("")
        self.frame_plr.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_plr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plr.setLineWidth(1)
        self.frame_plr.setObjectName("frame_plr")
        self.horizontalSlider_plr = QtWidgets.QSlider(self.frame_plr)
        self.horizontalSlider_plr.setGeometry(QtCore.QRect(12, 30, 131, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_plr.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_plr.setSizePolicy(sizePolicy)
        self.horizontalSlider_plr.setStyleSheet("selection-background-color: rgb(141, 70, 212);")
        self.horizontalSlider_plr.setMaximum(100)
        self.horizontalSlider_plr.setSingleStep(0)
        self.horizontalSlider_plr.setProperty("value", 67)
        self.horizontalSlider_plr.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_plr.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_plr.setObjectName("horizontalSlider_plr")
        self.label_33 = QtWidgets.QLabel(self.frame_plr)
        self.label_33.setGeometry(QtCore.QRect(55, 8, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.doubleSpinBox_plr = QtWidgets.QDoubleSpinBox(self.frame_plr)
        self.doubleSpinBox_plr.setGeometry(QtCore.QRect(10, 4, 49, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_plr.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_plr.setSizePolicy(sizePolicy)
        self.doubleSpinBox_plr.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox_plr.setFont(font)
        self.doubleSpinBox_plr.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_plr.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_plr.setDecimals(1)
        self.doubleSpinBox_plr.setMaximum(3.0)
        self.doubleSpinBox_plr.setSingleStep(0.1)
        self.doubleSpinBox_plr.setProperty("value", 2.0)
        self.doubleSpinBox_plr.setObjectName("doubleSpinBox_plr")
        self.label_34 = QtWidgets.QLabel(self.frame_plr)
        self.label_34.setGeometry(QtCore.QRect(47, 62, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.label_plr = QtWidgets.QLabel(self.frame_plr)
        self.label_plr.setEnabled(True)
        self.label_plr.setGeometry(QtCore.QRect(10, 58, 35, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_plr.sizePolicy().hasHeightForWidth())
        self.label_plr.setSizePolicy(sizePolicy)
        self.label_plr.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.label_plr.setFont(font)
        self.label_plr.setAutoFillBackground(False)
        self.label_plr.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(196, 193, 189);")
        self.label_plr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_plr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plr.setObjectName("label_plr")
        self.label_color_pul_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_color_pul_2.setGeometry(QtCore.QRect(606, 262, 150, 122))
        self.label_color_pul_2.setStyleSheet("background-color: rgb(136, 212, 152, 175);\n"
"border-radius: 10px;")
        self.label_color_pul_2.setText("")
        self.label_color_pul_2.setObjectName("label_color_pul_2")
        self.label_aur_color_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_aur_color_3.setGeometry(QtCore.QRect(796, 262, 150, 122))
        self.label_aur_color_3.setStyleSheet("background-color: rgb(170, 170, 255, 150);\n"
"border-radius: 10px;")
        self.label_aur_color_3.setText("")
        self.label_aur_color_3.setObjectName("label_aur_color_3")
        self.label_aul_color = QtWidgets.QLabel(self.centralWidget)
        self.label_aul_color.setGeometry(QtCore.QRect(272, 94, 150, 122))
        self.label_aul_color.setStyleSheet("background-color: rgba(216, 83, 25, 100);\n"
"background-color: rgb(231, 179, 156, 150);\n"
"background-color: rgba(221, 117, 72, 140);\n"
"background-color: rgb(220, 52, 50, 125);\n"
"border-radius: 10px;")
        self.label_aul_color.setText("")
        self.label_aul_color.setObjectName("label_aul_color")
        self.label_aur_color = QtWidgets.QLabel(self.centralWidget)
        self.label_aur_color.setGeometry(QtCore.QRect(82, 94, 150, 122))
        self.label_aur_color.setStyleSheet("background-color: rgba(0, 170, 255, 100);\n"
"background-color: rgb(52, 141, 200, 150);\n"
"background-color: rgb(53, 151, 255, 130);\n"
"border-radius: 10px;")
        self.label_aur_color.setText("")
        self.label_aur_color.setObjectName("label_aur_color")
        self.label_alr_color = QtWidgets.QLabel(self.centralWidget)
        self.label_alr_color.setGeometry(QtCore.QRect(82, 262, 150, 122))
        self.label_alr_color.setStyleSheet("background-color: rgba(236, 177, 32, 100);\n"
"background-color: rgb(170, 170, 255, 150);\n"
"border-radius: 10px;")
        self.label_alr_color.setText("")
        self.label_alr_color.setObjectName("label_alr_color")
        self.label_all_color = QtWidgets.QLabel(self.centralWidget)
        self.label_all_color.setGeometry(QtCore.QRect(272, 262, 150, 122))
        self.label_all_color.setStyleSheet("background-color: rgba(119, 172, 48, 100);\n"
"background-color: rgb(173, 206, 130, 150);\n"
"background-color: rgb(136, 212, 152, 175);\n"
"border-radius: 10px;")
        self.label_all_color.setText("")
        self.label_all_color.setObjectName("label_all_color")
        self.label_t_run.raise_()
        self.label_ant.raise_()
        self.label_alr_color.raise_()
        self.label_all_color.raise_()
        self.label_aur_color.raise_()
        self.label_aul_color.raise_()
        self.label_post.raise_()
        self.label_color_pul_2.raise_()
        self.label_aur_color_2.raise_()
        self.label_color_pul.raise_()
        self.label.raise_()
        self.pushButton_on.raise_()
        self.label_9.raise_()
        self.groupBox_alr.raise_()
        self.groupBox_aur.raise_()
        self.groupBox_all.raise_()
        self.groupBox_aul.raise_()
        self.label_21.raise_()
        self.label_alr_color_2.raise_()
        self.label_alr_color_3.raise_()
        self.label_alr_color_5.raise_()
        self.label_alr_color_6.raise_()
        self.label_alr_color_7.raise_()
        self.label_alr_color_8.raise_()
        self.label_alr_color_9.raise_()
        self.label_alr_color_10.raise_()
        self.label_alr_color_11.raise_()
        self.label_alr_color_12.raise_()
        self.label_t_run_2.raise_()
        self.label_35.raise_()
        self.groupBox_pul.raise_()
        self.label_4.raise_()
        self.label_alr_color_13.raise_()
        self.label_alr_color_14.raise_()
        self.groupBox_pur.raise_()
        self.groupBox_pll.raise_()
        self.label_aur_color_3.raise_()
        self.groupBox_plr.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1032, 25))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Anterior"))
        self.pushButton_on.setText(_translate("MainWindow", "Run"))
        self.label_9.setText(_translate("MainWindow", "Run Time:"))
        self.groupBox_alr.setTitle(_translate("MainWindow", "Lower Right"))
        self.label_16.setText(_translate("MainWindow", "setpoint (psi)"))
        self.label_17.setText(_translate("MainWindow", "current (psi)"))
        self.label_alr.setText(_translate("MainWindow", "0.0"))
        self.groupBox_aur.setTitle(_translate("MainWindow", "Upper Right"))
        self.label_19.setText(_translate("MainWindow", "setpoint (psi)"))
        self.label_20.setText(_translate("MainWindow", "current (psi)"))
        self.label_aur.setText(_translate("MainWindow", "0.0"))
        self.groupBox_all.setTitle(_translate("MainWindow", "Lower Left  "))
        self.label_22.setText(_translate("MainWindow", "setpoint (psi)"))
        self.label_23.setText(_translate("MainWindow", "current (psi)"))
        self.label_all.setText(_translate("MainWindow", "0.0"))
        self.groupBox_aul.setTitle(_translate("MainWindow", "Upper Left  "))
        self.label_25.setText(_translate("MainWindow", "setpoint (psi)"))
        self.label_26.setText(_translate("MainWindow", "current (psi)"))
        self.label_aul.setText(_translate("MainWindow", "0.0"))
        self.label_t_run.setText(_translate("MainWindow", "0.0"))
        self.label_21.setText(_translate("MainWindow", "(min)"))
        self.label_t_run_2.setText(_translate("MainWindow", "0.0"))
        self.label_35.setText(_translate("MainWindow", "(psi) accumulator"))
        self.groupBox_pul.setTitle(_translate("MainWindow", "Upper Left  "))
        self.label_28.setText(_translate("MainWindow", "setpoint (psi)"))
        self.label_29.setText(_translate("MainWindow", "current (psi)"))
        self.label_pul.setText(_translate("MainWindow", "0.0"))
        self.groupBox_pur.setTitle(_translate("MainWindow", "Upper Right"))
        self.label_30.setText(_translate("MainWindow", "setpoint (psi)"))
        self.label_31.setText(_translate("MainWindow", "current (psi)"))
        self.label_pur.setText(_translate("MainWindow", "0.0"))
        self.label_4.setText(_translate("MainWindow", "Posterior"))
        self.groupBox_pll.setTitle(_translate("MainWindow", "Lower Left  "))
        self.label_36.setText(_translate("MainWindow", "setpoint (psi)"))
        self.label_37.setText(_translate("MainWindow", "current (psi)"))
        self.label_pll.setText(_translate("MainWindow", "0.0"))
        self.groupBox_plr.setTitle(_translate("MainWindow", "Lower Right"))
        self.label_33.setText(_translate("MainWindow", "setpoint (psi)"))
        self.label_34.setText(_translate("MainWindow", "current (psi)"))
        self.label_plr.setText(_translate("MainWindow", "0.0"))

