# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/tunewindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(494, 331)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(21, 184, 78, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(131, 184, 78, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(380, 285, 85, 27))
        self.pushButton_save.setObjectName("pushButton_save")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(52, 28, 151, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(318, 28, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 221, 291))
        self.label.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 181, 248))
        self.label_2.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.doubleSpinBox__control__inflation__kd = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__control__inflation__kd.setGeometry(QtCore.QRect(32, 272, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__control__inflation__kd.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__control__inflation__kd.setSizePolicy(sizePolicy)
        self.doubleSpinBox__control__inflation__kd.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__control__inflation__kd.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__control__inflation__kd.setFont(font)
        self.doubleSpinBox__control__inflation__kd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__control__inflation__kd.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__control__inflation__kd.setDecimals(2)
        self.doubleSpinBox__control__inflation__kd.setMaximum(1000.0)
        self.doubleSpinBox__control__inflation__kd.setSingleStep(0.1)
        self.doubleSpinBox__control__inflation__kd.setObjectName("doubleSpinBox__control__inflation__kd")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(98, 277, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.doubleSpinBox__control__inflation__kp = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__control__inflation__kp.setGeometry(QtCore.QRect(32, 206, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__control__inflation__kp.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__control__inflation__kp.setSizePolicy(sizePolicy)
        self.doubleSpinBox__control__inflation__kp.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__control__inflation__kp.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__control__inflation__kp.setFont(font)
        self.doubleSpinBox__control__inflation__kp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__control__inflation__kp.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__control__inflation__kp.setDecimals(2)
        self.doubleSpinBox__control__inflation__kp.setMaximum(1000.0)
        self.doubleSpinBox__control__inflation__kp.setSingleStep(0.1)
        self.doubleSpinBox__control__inflation__kp.setObjectName("doubleSpinBox__control__inflation__kp")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(98, 210, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.doubleSpinBox__control__inflation__ki = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__control__inflation__ki.setGeometry(QtCore.QRect(32, 239, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__control__inflation__ki.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__control__inflation__ki.setSizePolicy(sizePolicy)
        self.doubleSpinBox__control__inflation__ki.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__control__inflation__ki.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__control__inflation__ki.setFont(font)
        self.doubleSpinBox__control__inflation__ki.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__control__inflation__ki.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__control__inflation__ki.setDecimals(2)
        self.doubleSpinBox__control__inflation__ki.setMaximum(1000.0)
        self.doubleSpinBox__control__inflation__ki.setSingleStep(0.1)
        self.doubleSpinBox__control__inflation__ki.setObjectName("doubleSpinBox__control__inflation__ki")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(98, 244, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.doubleSpinBox__control__deflation__kd = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__control__deflation__kd.setGeometry(QtCore.QRect(141, 272, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__control__deflation__kd.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__control__deflation__kd.setSizePolicy(sizePolicy)
        self.doubleSpinBox__control__deflation__kd.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__control__deflation__kd.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__control__deflation__kd.setFont(font)
        self.doubleSpinBox__control__deflation__kd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__control__deflation__kd.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__control__deflation__kd.setDecimals(2)
        self.doubleSpinBox__control__deflation__kd.setMaximum(1000.0)
        self.doubleSpinBox__control__deflation__kd.setSingleStep(0.1)
        self.doubleSpinBox__control__deflation__kd.setObjectName("doubleSpinBox__control__deflation__kd")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(207, 211, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.doubleSpinBox__control__deflation__ki = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__control__deflation__ki.setGeometry(QtCore.QRect(141, 239, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__control__deflation__ki.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__control__deflation__ki.setSizePolicy(sizePolicy)
        self.doubleSpinBox__control__deflation__ki.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__control__deflation__ki.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__control__deflation__ki.setFont(font)
        self.doubleSpinBox__control__deflation__ki.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__control__deflation__ki.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__control__deflation__ki.setDecimals(2)
        self.doubleSpinBox__control__deflation__ki.setMaximum(1000.0)
        self.doubleSpinBox__control__deflation__ki.setSingleStep(0.1)
        self.doubleSpinBox__control__deflation__ki.setObjectName("doubleSpinBox__control__deflation__ki")
        self.doubleSpinBox__control__deflation__kp = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__control__deflation__kp.setGeometry(QtCore.QRect(141, 206, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__control__deflation__kp.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__control__deflation__kp.setSizePolicy(sizePolicy)
        self.doubleSpinBox__control__deflation__kp.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__control__deflation__kp.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__control__deflation__kp.setFont(font)
        self.doubleSpinBox__control__deflation__kp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__control__deflation__kp.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__control__deflation__kp.setDecimals(2)
        self.doubleSpinBox__control__deflation__kp.setMaximum(1000.0)
        self.doubleSpinBox__control__deflation__kp.setSingleStep(0.1)
        self.doubleSpinBox__control__deflation__kp.setObjectName("doubleSpinBox__control__deflation__kp")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(207, 244, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(207, 277, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(97, 132, 99, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.doubleSpinBox__control__noise_threshold = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__control__noise_threshold.setGeometry(QtCore.QRect(31, 61, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__control__noise_threshold.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__control__noise_threshold.setSizePolicy(sizePolicy)
        self.doubleSpinBox__control__noise_threshold.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__control__noise_threshold.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__control__noise_threshold.setFont(font)
        self.doubleSpinBox__control__noise_threshold.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__control__noise_threshold.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__control__noise_threshold.setDecimals(2)
        self.doubleSpinBox__control__noise_threshold.setMaximum(1000.0)
        self.doubleSpinBox__control__noise_threshold.setSingleStep(0.1)
        self.doubleSpinBox__control__noise_threshold.setObjectName("doubleSpinBox__control__noise_threshold")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(97, 99, 128, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(97, 66, 117, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.doubleSpinBox__control__windup_limit = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__control__windup_limit.setGeometry(QtCore.QRect(31, 127, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__control__windup_limit.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__control__windup_limit.setSizePolicy(sizePolicy)
        self.doubleSpinBox__control__windup_limit.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__control__windup_limit.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__control__windup_limit.setFont(font)
        self.doubleSpinBox__control__windup_limit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__control__windup_limit.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__control__windup_limit.setDecimals(0)
        self.doubleSpinBox__control__windup_limit.setMaximum(1000.0)
        self.doubleSpinBox__control__windup_limit.setSingleStep(1.0)
        self.doubleSpinBox__control__windup_limit.setObjectName("doubleSpinBox__control__windup_limit")
        self.doubleSpinBox__control__differential_gap = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__control__differential_gap.setGeometry(QtCore.QRect(31, 94, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__control__differential_gap.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__control__differential_gap.setSizePolicy(sizePolicy)
        self.doubleSpinBox__control__differential_gap.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__control__differential_gap.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__control__differential_gap.setFont(font)
        self.doubleSpinBox__control__differential_gap.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__control__differential_gap.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__control__differential_gap.setDecimals(2)
        self.doubleSpinBox__control__differential_gap.setMaximum(1000.0)
        self.doubleSpinBox__control__differential_gap.setSingleStep(0.1)
        self.doubleSpinBox__control__differential_gap.setObjectName("doubleSpinBox__control__differential_gap")
        self.doubleSpinBox__freq__display = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__freq__display.setGeometry(QtCore.QRect(303, 94, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__freq__display.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__freq__display.setSizePolicy(sizePolicy)
        self.doubleSpinBox__freq__display.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__freq__display.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__freq__display.setFont(font)
        self.doubleSpinBox__freq__display.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__freq__display.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__freq__display.setDecimals(1)
        self.doubleSpinBox__freq__display.setMaximum(1000.0)
        self.doubleSpinBox__freq__display.setSingleStep(1.0)
        self.doubleSpinBox__freq__display.setObjectName("doubleSpinBox__freq__display")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(369, 100, 67, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.doubleSpinBox__freq__control = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__freq__control.setGeometry(QtCore.QRect(303, 127, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__freq__control.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__freq__control.setSizePolicy(sizePolicy)
        self.doubleSpinBox__freq__control.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__freq__control.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__freq__control.setFont(font)
        self.doubleSpinBox__freq__control.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__freq__control.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__freq__control.setDecimals(1)
        self.doubleSpinBox__freq__control.setMaximum(1000.0)
        self.doubleSpinBox__freq__control.setSingleStep(1.0)
        self.doubleSpinBox__freq__control.setObjectName("doubleSpinBox__freq__control")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(369, 133, 67, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.doubleSpinBox__freq__log = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__freq__log.setGeometry(QtCore.QRect(303, 160, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__freq__log.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__freq__log.setSizePolicy(sizePolicy)
        self.doubleSpinBox__freq__log.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__freq__log.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__freq__log.setFont(font)
        self.doubleSpinBox__freq__log.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__freq__log.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__freq__log.setDecimals(1)
        self.doubleSpinBox__freq__log.setMaximum(1000.0)
        self.doubleSpinBox__freq__log.setSingleStep(1.0)
        self.doubleSpinBox__freq__log.setObjectName("doubleSpinBox__freq__log")
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setGeometry(QtCore.QRect(369, 166, 45, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.doubleSpinBox__freq__pwm = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__freq__pwm.setGeometry(QtCore.QRect(303, 193, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__freq__pwm.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__freq__pwm.setSizePolicy(sizePolicy)
        self.doubleSpinBox__freq__pwm.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__freq__pwm.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__freq__pwm.setFont(font)
        self.doubleSpinBox__freq__pwm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__freq__pwm.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__freq__pwm.setDecimals(1)
        self.doubleSpinBox__freq__pwm.setMaximum(1000.0)
        self.doubleSpinBox__freq__pwm.setSingleStep(1.0)
        self.doubleSpinBox__freq__pwm.setObjectName("doubleSpinBox__freq__pwm")
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(369, 199, 90, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.doubleSpinBox__freq__sense = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__freq__sense.setGeometry(QtCore.QRect(303, 61, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__freq__sense.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__freq__sense.setSizePolicy(sizePolicy)
        self.doubleSpinBox__freq__sense.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__freq__sense.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox__freq__sense.setFont(font)
        self.doubleSpinBox__freq__sense.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__freq__sense.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__freq__sense.setDecimals(1)
        self.doubleSpinBox__freq__sense.setMaximum(1000.0)
        self.doubleSpinBox__freq__sense.setSingleStep(1.0)
        self.doubleSpinBox__freq__sense.setObjectName("doubleSpinBox__freq__sense")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(369, 67, 61, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.pushButton_update = QtWidgets.QPushButton(Form)
        self.pushButton_update.setGeometry(QtCore.QRect(304, 230, 154, 27))
        self.pushButton_update.setObjectName("pushButton_update")
        self.label_2.raise_()
        self.doubleSpinBox__freq__display.raise_()
        self.label_29.raise_()
        self.doubleSpinBox__freq__control.raise_()
        self.label_31.raise_()
        self.doubleSpinBox__freq__log.raise_()
        self.label_32.raise_()
        self.doubleSpinBox__freq__pwm.raise_()
        self.label_33.raise_()
        self.doubleSpinBox__freq__sense.raise_()
        self.label_30.raise_()
        self.label.raise_()
        self.label_24.raise_()
        self.doubleSpinBox__control__noise_threshold.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.doubleSpinBox__control__windup_limit.raise_()
        self.doubleSpinBox__control__differential_gap.raise_()
        self.doubleSpinBox__control__inflation__kd.raise_()
        self.label_18.raise_()
        self.doubleSpinBox__control__inflation__kp.raise_()
        self.label_16.raise_()
        self.doubleSpinBox__control__inflation__ki.raise_()
        self.label_17.raise_()
        self.doubleSpinBox__control__deflation__kd.raise_()
        self.label_21.raise_()
        self.doubleSpinBox__control__deflation__ki.raise_()
        self.doubleSpinBox__control__deflation__kp.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_20.raise_()
        self.pushButton_save.raise_()
        self.label_27.raise_()
        self.label_19.raise_()
        self.label_28.raise_()
        self.pushButton_update.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_19.setText(_translate("Form", "Inflation"))
        self.label_20.setText(_translate("Form", "Deflation"))
        self.pushButton_save.setText(_translate("Form", "Save"))
        self.label_27.setText(_translate("Form", "Control Parameters"))
        self.label_28.setText(_translate("Form", "System Timing"))
        self.label_18.setText(_translate("Form", "Kd"))
        self.label_16.setText(_translate("Form", "Kp"))
        self.label_17.setText(_translate("Form", "Ki"))
        self.label_21.setText(_translate("Form", "Kp"))
        self.label_22.setText(_translate("Form", "Ki"))
        self.label_23.setText(_translate("Form", "Kd"))
        self.label_24.setText(_translate("Form", "(psi) windup limit"))
        self.label_25.setText(_translate("Form", "(psi ±) differential gap"))
        self.label_26.setText(_translate("Form", "(psi) noise threshold"))
        self.label_29.setText(_translate("Form", "(Hz) display"))
        self.label_31.setText(_translate("Form", "(Hz) control"))
        self.label_32.setText(_translate("Form", "(Hz) log"))
        self.label_33.setText(_translate("Form", "(Hz) valve PWM"))
        self.label_30.setText(_translate("Form", "(Hz) sense"))
        self.pushButton_update.setText(_translate("Form", "Update"))

