# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/tunewindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(723, 366)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(25, 220, 78, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(135, 220, 78, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(617, 320, 85, 27))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(46, 28, 161, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(543, 28, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 222, 326))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(518, 20, 183, 248))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.doubleSpinBox__chamber__inflate__kd = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__chamber__inflate__kd.setGeometry(QtCore.QRect(36, 308, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__chamber__inflate__kd.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__chamber__inflate__kd.setSizePolicy(sizePolicy)
        self.doubleSpinBox__chamber__inflate__kd.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__chamber__inflate__kd.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__chamber__inflate__kd.setFont(font)
        self.doubleSpinBox__chamber__inflate__kd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__chamber__inflate__kd.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__chamber__inflate__kd.setDecimals(2)
        self.doubleSpinBox__chamber__inflate__kd.setMaximum(1000.0)
        self.doubleSpinBox__chamber__inflate__kd.setSingleStep(0.1)
        self.doubleSpinBox__chamber__inflate__kd.setObjectName("doubleSpinBox__chamber__inflate__kd")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(102, 313, 21, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.doubleSpinBox__chamber__inflate__kp = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__chamber__inflate__kp.setGeometry(QtCore.QRect(36, 242, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__chamber__inflate__kp.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__chamber__inflate__kp.setSizePolicy(sizePolicy)
        self.doubleSpinBox__chamber__inflate__kp.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__chamber__inflate__kp.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__chamber__inflate__kp.setFont(font)
        self.doubleSpinBox__chamber__inflate__kp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__chamber__inflate__kp.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__chamber__inflate__kp.setDecimals(2)
        self.doubleSpinBox__chamber__inflate__kp.setMaximum(1000.0)
        self.doubleSpinBox__chamber__inflate__kp.setSingleStep(0.1)
        self.doubleSpinBox__chamber__inflate__kp.setObjectName("doubleSpinBox__chamber__inflate__kp")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(102, 246, 21, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.doubleSpinBox__chamber__inflate__ki = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__chamber__inflate__ki.setGeometry(QtCore.QRect(36, 275, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__chamber__inflate__ki.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__chamber__inflate__ki.setSizePolicy(sizePolicy)
        self.doubleSpinBox__chamber__inflate__ki.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__chamber__inflate__ki.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__chamber__inflate__ki.setFont(font)
        self.doubleSpinBox__chamber__inflate__ki.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__chamber__inflate__ki.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__chamber__inflate__ki.setDecimals(2)
        self.doubleSpinBox__chamber__inflate__ki.setMaximum(1000.0)
        self.doubleSpinBox__chamber__inflate__ki.setSingleStep(0.1)
        self.doubleSpinBox__chamber__inflate__ki.setObjectName("doubleSpinBox__chamber__inflate__ki")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(102, 280, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.doubleSpinBox__chamber__deflate__kd = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__chamber__deflate__kd.setGeometry(QtCore.QRect(145, 308, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__chamber__deflate__kd.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__chamber__deflate__kd.setSizePolicy(sizePolicy)
        self.doubleSpinBox__chamber__deflate__kd.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__chamber__deflate__kd.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__chamber__deflate__kd.setFont(font)
        self.doubleSpinBox__chamber__deflate__kd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__chamber__deflate__kd.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__chamber__deflate__kd.setDecimals(2)
        self.doubleSpinBox__chamber__deflate__kd.setMaximum(1000.0)
        self.doubleSpinBox__chamber__deflate__kd.setSingleStep(0.1)
        self.doubleSpinBox__chamber__deflate__kd.setObjectName("doubleSpinBox__chamber__deflate__kd")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(211, 247, 21, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.doubleSpinBox__chamber__deflate__ki = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__chamber__deflate__ki.setGeometry(QtCore.QRect(145, 275, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__chamber__deflate__ki.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__chamber__deflate__ki.setSizePolicy(sizePolicy)
        self.doubleSpinBox__chamber__deflate__ki.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__chamber__deflate__ki.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__chamber__deflate__ki.setFont(font)
        self.doubleSpinBox__chamber__deflate__ki.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__chamber__deflate__ki.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__chamber__deflate__ki.setDecimals(2)
        self.doubleSpinBox__chamber__deflate__ki.setMaximum(1000.0)
        self.doubleSpinBox__chamber__deflate__ki.setSingleStep(0.1)
        self.doubleSpinBox__chamber__deflate__ki.setObjectName("doubleSpinBox__chamber__deflate__ki")
        self.doubleSpinBox__chamber__deflate__kp = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__chamber__deflate__kp.setGeometry(QtCore.QRect(145, 242, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__chamber__deflate__kp.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__chamber__deflate__kp.setSizePolicy(sizePolicy)
        self.doubleSpinBox__chamber__deflate__kp.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__chamber__deflate__kp.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__chamber__deflate__kp.setFont(font)
        self.doubleSpinBox__chamber__deflate__kp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__chamber__deflate__kp.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__chamber__deflate__kp.setDecimals(2)
        self.doubleSpinBox__chamber__deflate__kp.setMaximum(1000.0)
        self.doubleSpinBox__chamber__deflate__kp.setSingleStep(0.1)
        self.doubleSpinBox__chamber__deflate__kp.setObjectName("doubleSpinBox__chamber__deflate__kp")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(211, 280, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(211, 313, 21, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(96, 166, 131, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.doubleSpinBox__chamber__noise_threshold = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__chamber__noise_threshold.setGeometry(QtCore.QRect(30, 94, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__chamber__noise_threshold.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__chamber__noise_threshold.setSizePolicy(sizePolicy)
        self.doubleSpinBox__chamber__noise_threshold.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__chamber__noise_threshold.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__chamber__noise_threshold.setFont(font)
        self.doubleSpinBox__chamber__noise_threshold.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__chamber__noise_threshold.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__chamber__noise_threshold.setDecimals(2)
        self.doubleSpinBox__chamber__noise_threshold.setMaximum(1000.0)
        self.doubleSpinBox__chamber__noise_threshold.setSingleStep(0.1)
        self.doubleSpinBox__chamber__noise_threshold.setObjectName("doubleSpinBox__chamber__noise_threshold")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(96, 133, 141, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(96, 100, 141, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.doubleSpinBox__chamber__windup_limit = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__chamber__windup_limit.setGeometry(QtCore.QRect(30, 160, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__chamber__windup_limit.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__chamber__windup_limit.setSizePolicy(sizePolicy)
        self.doubleSpinBox__chamber__windup_limit.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__chamber__windup_limit.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__chamber__windup_limit.setFont(font)
        self.doubleSpinBox__chamber__windup_limit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__chamber__windup_limit.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__chamber__windup_limit.setDecimals(0)
        self.doubleSpinBox__chamber__windup_limit.setMaximum(1000.0)
        self.doubleSpinBox__chamber__windup_limit.setSingleStep(1.0)
        self.doubleSpinBox__chamber__windup_limit.setObjectName("doubleSpinBox__chamber__windup_limit")
        self.doubleSpinBox__chamber__differential_gap = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__chamber__differential_gap.setGeometry(QtCore.QRect(30, 127, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__chamber__differential_gap.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__chamber__differential_gap.setSizePolicy(sizePolicy)
        self.doubleSpinBox__chamber__differential_gap.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__chamber__differential_gap.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__chamber__differential_gap.setFont(font)
        self.doubleSpinBox__chamber__differential_gap.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__chamber__differential_gap.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__chamber__differential_gap.setDecimals(2)
        self.doubleSpinBox__chamber__differential_gap.setMaximum(1000.0)
        self.doubleSpinBox__chamber__differential_gap.setSingleStep(0.1)
        self.doubleSpinBox__chamber__differential_gap.setObjectName("doubleSpinBox__chamber__differential_gap")
        self.doubleSpinBox__freq__display = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__freq__display.setGeometry(QtCore.QRect(528, 94, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__freq__display.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__freq__display.setSizePolicy(sizePolicy)
        self.doubleSpinBox__freq__display.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__freq__display.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__freq__display.setFont(font)
        self.doubleSpinBox__freq__display.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__freq__display.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__freq__display.setDecimals(1)
        self.doubleSpinBox__freq__display.setMaximum(1000.0)
        self.doubleSpinBox__freq__display.setSingleStep(1.0)
        self.doubleSpinBox__freq__display.setObjectName("doubleSpinBox__freq__display")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(594, 100, 81, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.doubleSpinBox__freq__control = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__freq__control.setGeometry(QtCore.QRect(528, 127, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__freq__control.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__freq__control.setSizePolicy(sizePolicy)
        self.doubleSpinBox__freq__control.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__freq__control.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__freq__control.setFont(font)
        self.doubleSpinBox__freq__control.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__freq__control.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__freq__control.setDecimals(1)
        self.doubleSpinBox__freq__control.setMaximum(1000.0)
        self.doubleSpinBox__freq__control.setSingleStep(1.0)
        self.doubleSpinBox__freq__control.setObjectName("doubleSpinBox__freq__control")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(594, 133, 91, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.doubleSpinBox__freq__log = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__freq__log.setGeometry(QtCore.QRect(528, 160, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__freq__log.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__freq__log.setSizePolicy(sizePolicy)
        self.doubleSpinBox__freq__log.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__freq__log.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__freq__log.setFont(font)
        self.doubleSpinBox__freq__log.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__freq__log.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__freq__log.setDecimals(1)
        self.doubleSpinBox__freq__log.setMaximum(1000.0)
        self.doubleSpinBox__freq__log.setSingleStep(1.0)
        self.doubleSpinBox__freq__log.setObjectName("doubleSpinBox__freq__log")
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setGeometry(QtCore.QRect(594, 166, 71, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.doubleSpinBox__freq__pwm = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__freq__pwm.setGeometry(QtCore.QRect(528, 193, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__freq__pwm.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__freq__pwm.setSizePolicy(sizePolicy)
        self.doubleSpinBox__freq__pwm.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__freq__pwm.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__freq__pwm.setFont(font)
        self.doubleSpinBox__freq__pwm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__freq__pwm.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__freq__pwm.setDecimals(1)
        self.doubleSpinBox__freq__pwm.setMaximum(1000.0)
        self.doubleSpinBox__freq__pwm.setSingleStep(1.0)
        self.doubleSpinBox__freq__pwm.setObjectName("doubleSpinBox__freq__pwm")
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(594, 199, 101, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.doubleSpinBox__freq__sense = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__freq__sense.setGeometry(QtCore.QRect(528, 61, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__freq__sense.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__freq__sense.setSizePolicy(sizePolicy)
        self.doubleSpinBox__freq__sense.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__freq__sense.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__freq__sense.setFont(font)
        self.doubleSpinBox__freq__sense.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__freq__sense.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__freq__sense.setDecimals(1)
        self.doubleSpinBox__freq__sense.setMaximum(1000.0)
        self.doubleSpinBox__freq__sense.setSingleStep(1.0)
        self.doubleSpinBox__freq__sense.setObjectName("doubleSpinBox__freq__sense")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(594, 67, 81, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.pushButton_update = QtWidgets.QPushButton(Form)
        self.pushButton_update.setGeometry(QtCore.QRect(531, 230, 160, 27))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.pushButton_update.setFont(font)
        self.pushButton_update.setObjectName("pushButton_update")
        self.doubleSpinBox__chamber__deadzone = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__chamber__deadzone.setGeometry(QtCore.QRect(30, 61, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__chamber__deadzone.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__chamber__deadzone.setSizePolicy(sizePolicy)
        self.doubleSpinBox__chamber__deadzone.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__chamber__deadzone.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__chamber__deadzone.setFont(font)
        self.doubleSpinBox__chamber__deadzone.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__chamber__deadzone.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__chamber__deadzone.setDecimals(1)
        self.doubleSpinBox__chamber__deadzone.setMaximum(1000.0)
        self.doubleSpinBox__chamber__deadzone.setSingleStep(1.0)
        self.doubleSpinBox__chamber__deadzone.setObjectName("doubleSpinBox__chamber__deadzone")
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setGeometry(QtCore.QRect(96, 67, 131, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(Form)
        self.label_36.setGeometry(QtCore.QRect(345, 67, 151, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.doubleSpinBox__accum__setpoint = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__accum__setpoint.setGeometry(QtCore.QRect(279, 61, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__accum__setpoint.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__accum__setpoint.setSizePolicy(sizePolicy)
        self.doubleSpinBox__accum__setpoint.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__accum__setpoint.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__accum__setpoint.setFont(font)
        self.doubleSpinBox__accum__setpoint.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__accum__setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__accum__setpoint.setDecimals(1)
        self.doubleSpinBox__accum__setpoint.setMaximum(1000.0)
        self.doubleSpinBox__accum__setpoint.setSingleStep(1.0)
        self.doubleSpinBox__accum__setpoint.setObjectName("doubleSpinBox__accum__setpoint")
        self.doubleSpinBox__accum__differential_gap = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox__accum__differential_gap.setGeometry(QtCore.QRect(279, 95, 60, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox__accum__differential_gap.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox__accum__differential_gap.setSizePolicy(sizePolicy)
        self.doubleSpinBox__accum__differential_gap.setMinimumSize(QtCore.QSize(60, 27))
        self.doubleSpinBox__accum__differential_gap.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        self.doubleSpinBox__accum__differential_gap.setFont(font)
        self.doubleSpinBox__accum__differential_gap.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox__accum__differential_gap.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__accum__differential_gap.setDecimals(1)
        self.doubleSpinBox__accum__differential_gap.setMaximum(1000.0)
        self.doubleSpinBox__accum__differential_gap.setSingleStep(1.0)
        self.doubleSpinBox__accum__differential_gap.setObjectName("doubleSpinBox__accum__differential_gap")
        self.label_37 = QtWidgets.QLabel(Form)
        self.label_37.setGeometry(QtCore.QRect(345, 101, 151, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(Form)
        self.label_38.setGeometry(QtCore.QRect(279, 28, 191, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(269, 20, 222, 112))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-radius: 10px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label_2.raise_()
        self.doubleSpinBox__freq__display.raise_()
        self.label_29.raise_()
        self.doubleSpinBox__freq__control.raise_()
        self.label_31.raise_()
        self.doubleSpinBox__freq__log.raise_()
        self.label_32.raise_()
        self.doubleSpinBox__freq__pwm.raise_()
        self.label_33.raise_()
        self.doubleSpinBox__freq__sense.raise_()
        self.label_30.raise_()
        self.label.raise_()
        self.label_24.raise_()
        self.doubleSpinBox__chamber__noise_threshold.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.doubleSpinBox__chamber__windup_limit.raise_()
        self.doubleSpinBox__chamber__differential_gap.raise_()
        self.doubleSpinBox__chamber__inflate__kd.raise_()
        self.label_18.raise_()
        self.doubleSpinBox__chamber__inflate__kp.raise_()
        self.label_16.raise_()
        self.doubleSpinBox__chamber__inflate__ki.raise_()
        self.label_17.raise_()
        self.doubleSpinBox__chamber__deflate__kd.raise_()
        self.label_21.raise_()
        self.doubleSpinBox__chamber__deflate__ki.raise_()
        self.doubleSpinBox__chamber__deflate__kp.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_20.raise_()
        self.pushButton_save.raise_()
        self.label_27.raise_()
        self.label_19.raise_()
        self.label_28.raise_()
        self.pushButton_update.raise_()
        self.doubleSpinBox__chamber__deadzone.raise_()
        self.label_34.raise_()
        self.label_36.raise_()
        self.doubleSpinBox__accum__setpoint.raise_()
        self.doubleSpinBox__accum__differential_gap.raise_()
        self.label_37.raise_()
        self.label_38.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_19.setText(_translate("Form", "Inflation"))
        self.label_20.setText(_translate("Form", "Deflation"))
        self.pushButton_save.setText(_translate("Form", "Save"))
        self.label_27.setText(_translate("Form", "Chamber Parameters"))
        self.label_28.setText(_translate("Form", "System Timing"))
        self.label_18.setText(_translate("Form", "Kd"))
        self.label_16.setText(_translate("Form", "Kp"))
        self.label_17.setText(_translate("Form", "Ki"))
        self.label_21.setText(_translate("Form", "Kp"))
        self.label_22.setText(_translate("Form", "Ki"))
        self.label_23.setText(_translate("Form", "Kd"))
        self.label_24.setText(_translate("Form", "(psi) windup limit"))
        self.label_25.setText(_translate("Form", "(psi ±) differential gap"))
        self.label_26.setText(_translate("Form", "(psi) noise threshold"))
        self.label_29.setText(_translate("Form", "(Hz) display"))
        self.label_31.setText(_translate("Form", "(Hz) control"))
        self.label_32.setText(_translate("Form", "(Hz) log"))
        self.label_33.setText(_translate("Form", "(Hz) valve PWM"))
        self.label_30.setText(_translate("Form", "(Hz) sense"))
        self.pushButton_update.setText(_translate("Form", "Update"))
        self.label_34.setText(_translate("Form", "(% duty) deadzone"))
        self.label_36.setText(_translate("Form", "(psi) setpoint"))
        self.label_37.setText(_translate("Form", "(psi ±) differential gap"))
        self.label_38.setText(_translate("Form", "Accumulator Parameters"))

