ar: # chamber acronym (Anterior Right)
    adc: 0 # ADC channel for pressure sensor
    pwm: 
        inflate: 0 # PWM channel for inflation valve
        deflate: 4 # PWM channel for deflation valve
al:
    adc: 1
    pwm: 
        inflate: 1
        deflate: 5 
pr:
    adc: 2
    pwm: 
        inflate: 2
        deflate: 6
pl:
    adc: 3
    pwm: 
        inflate: 3
        deflate: 7